[toolchain]
anchor_version = "0.31.1"
solana_version = "2.3.13"
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
launchpad = "5rmCGbiPqdEfeqRp21W5VbVE9yVT7rNZEhSuEAmPUngk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/test.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "127.0.0.1"
url = "https://api.mainnet-beta.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.account]]
address = "HdqGCsprdhmgqaCXjJzGnKib2SGQvmT9XKYmR7ZjMqmi"
filename = "genesis/config.json"

[[test.validator.account]]
address = "3Mntzwtif7X8wJD5dz1EHRJSEqzrTfvEhQqrLmTDxBEy"
filename = "genesis/private-config.json"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[[test.validator.clone]]
address = "LBUZKhRxPF3XUpBCjp4YzTKgLccjZhTSDM9YuVaPwxo"

[[test.validator.clone]]
address = "cpamdpZCGKUy5JxQXB4dcpGPiikHawvSWAd6mEn1sGG"
